# Your Name or Company
title: Qiusi Yan

# Description of your website. This is used for social sharing.
description:  Qiusi Yan's homepage

# A brief blurb about yourself
content: I am an PhD candidate of Law in Peking University and an incoming PhD student of Management.<br><br><img src="https://s2.loli.net/2024/06/29/Lz14MrYjbhnUyKs.png" width="80" height="80">

# Add your social links
social:
  - platform: CV
    url: https://drive.google.com/file/d/1lHIhehmCmhSzimlN-8LV_96c7bfBOKsL/view

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
