# Your Name or Company
title: Qiusi Yan

# Description of your website. This is used for social sharing.
description:  Qiusi Yan's homepage

# A brief blurb about yourself
content: I am a Ph.D. candidate at the Law School of Peking University, specializing in Economic Law with a focus on Labor Law. My doctoral advisor is Professor Ye Jingyi. Prior to this, I completed my Master’s degree at Peking University Law School. Before pursuing law, I earned a Bachelor's degree in Management with a specialization in Organizational Behavior from the University of Science and Technology Beijing.

My research interests lie at the intersection of law and management, particularly in the professional domain. This interdisciplinary focus reflects my passion for combining insights from both fields. Motivated by my interest in cross-disciplinary research, I am also applying for a Ph.D. program in Management to further explore these connections and contribute to the evolving understanding of labor and organizational dynamics.

Contact: yanqiusi@pku.edu.cn<br><br><img src="https://s2.loli.net/2024/06/29/Lz14MrYjbhnUyKs.png" width="80" height="80">

# Add your social links
social:
  - platform: CV
    url: https://drive.google.com/file/d/1lHIhehmCmhSzimlN-8LV_96c7bfBOKsL/view

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
